### PR TITLE
GHA: Test pip install with Mingw64 python and gcc

### PR DESCRIPTION
**Pull request by jeromerobert**
Add a test for https://github.com/pybind/pybind11/pull/2921

### CODE REVIEW

**Comment by jeromerobert** [comment]
This willl fail until https://github.com/pybind/pybind11/pull/2921 reach PyPI, so I tag this PR as draft.

**Comment by jeromerobert** [comment]
pybind11 2.7.0 is now released, so https://github.com/pybind/pybind11/pull/2921 reach PyPI, so this PR is ready for merge.

**Comment by henryiii** [comment]
Possibly sysconfig tells you what Python was built with, not what you are targeting? (Which probably requires a customization to the build command)?

**Comment by jeromerobert** [comment]
`sysconfig.get_platform()` is not `mingw` anymore, so I need to do a new PR in https://github.com/pybind/pybind11 😭. See
<https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-python/0099-Change-the-get_platform-method-in-sysconfig-and-dist.patch>.

**Comment by jeromerobert** [comment]
And this commit https://github.com/pybind/pybind11/commit/3ac690b88 also need a fix for mingw.

**Comment by jeromerobert** [comment]
It's better to have this in the core repository so the Mingw build is continously tested. PR Moved here: https://github.com/pybind/pybind11/pull/3132

**Pull request merged**
