### PR TITLE
Update example for pybind11 v2.2

### PR DESCRIPTION
**Pull request by dean0x7d**
Also updates CI config. Changes match https://github.com/pybind/cmake_example/commit/8818f493e3698a3ab936cdd8e7144afae85df3f8

### CODE REVIEW

**Comment by dean0x7d** [comment]
The `conda` tests are failing because pybind11 v2.2 hasn't made it to conda-forge yet.

**Comment by wjakob** [comment]
It's not working for some reason (https://github.com/conda-forge/pybind11-feedstock/issues/20).

**Comment by dean0x7d** [comment]
OK, this is ready. All the tests pass now.

**Comment by wjakob** [comment]
LGTM!

**Comment by dean0x7d** [comment]
@wjakob Could you merge this? I don't have write access for this repo.

**Comment by SylvainCorlay** [comment]
I could merge but I don't have the privileges to add you on the repo.

**Comment by wjakob** [comment]
Oops, that doesn't sound right. I added @dean0x7d and @jagerman.

**Comment by dean0x7d** [comment]
Thanks!

**Pull request merged**
