### PR TITLE
Use define_macros for macros

### PR DESCRIPTION
**Pull request by isuruf**
Moves `VERSION_INFO` to `define_macros`
Copies `stdlib` flag to link time as well.

### CODE REVIEW

**Comment by isuruf** [comment]
Ready for review.

**Comment by isuruf** [comment]
Ping

**Comment by wjakob** [comment]
Apologies for the long delay. This PR seems to be somewhat garbled relative to 'master' -- could you rebase it? Also, it would be great to have some summary of why you are making those changes? (it wasn't immediately clear to me.)

**Comment by isuruf** [comment]
This is ready for review now

**Comment by wjakob** [comment]
This looks good. GitHub wasn't willing to merge this PR due to conflicts, so I just did so directly.

**Comment by isuruf** [comment]
Thanks

**Pull request closed without merging**
