### PR TITLE
Set __version__ string

### PR DESCRIPTION
**Pull request by SylvainCorlay**
- rename `py` directory to `src` to align with cmake example
- add `__version__` string in example.

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
Will merge if it looks god to either @wjakob or @dean0x7d

**Comment by wjakob** [comment]
LGTM, thanks

**Comment by dean0x7d** [comment]
Why not get the version from `build_ext` like this?
```python
opts.append('-DVERSION_INFO="%s"' % self.distribution.get_version())
```

It would be one less variable to keep track of explicitly and also makes the derived `BuildExt` portable since it doesn't rely on the capture.

**Comment by SylvainCorlay** [comment]
Good idea. Done.

**Pull request merged**
